version: "3.8"
services:
  database:
    container_name: database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: symfony_docker
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - '4306:3306'
    volumes:
      - ./mysql:/var/lib/mysql

  php:
    container_name: php
    build:
      context: ./php
    ports:
      - '9000:9000'
      - '1700:1700'  # Add this line for WebSocket

    environment:
      MERCURE_URL: ${MERCURE_URL:-http://mercure/.well-known/mercure}
      MERCURE_PUBLIC_URL: ${MERCURE_PUBLIC_URL:-http://localhost:81/.well-known/mercure}
      MERCURE_JWT_SECRET: ${MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
    volumes:
      - ./app:/var/www/symfony_docker
    depends_on:
      - database

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./app:/var/www/symfony_docker
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database

  mercure:
    container_name: mercure
    image: dunglas/mercure
    restart: unless-stopped
    environment:
      # Mandatory
      SERVER_NAME: ':80'
      MERCURE_PUBLISHER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
      MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
    ports:
      - "81:80"
    volumes:
      - mercure_data:/data
      - ./mercure/Caddyfile:/etc/caddy/Caddyfile  # Mount the Caddyfile
    command: /usr/bin/caddy run --config /etc/caddy/Caddyfile

volumes:
  mercure_data: {}
  mysql: {}